apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tp9-argocd
resources:
- ../base
images:
- name: ghcr.io/1223812789/spring-petclinic
  newName: ghcr.io/1223812789/spring-petclinic
  newTag: 716975c58e28b62f91d7ab9cd003a38d140d3329
patches:
- path: replicas.yaml
  target:
    group: apps
    kind: Deployment
    name: petclinic
    version: v1
- path: patch-routing.yaml
